CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 100 INCREMENT BY 1;
CREATE TABLE user ( id Integer PRIMARY KEY, fullname VARCHAR(200), username VARCHAR(20), password_hash VARCHAR(256), last_update TIMESTAMP);
