CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 100 INCREMENT BY 1;
CREATE TABLE user ( id Integer PRIMARY KEY, mail VARCHAR(20), password_hash VARCHAR(256), fullname VARCHAR(200), age Integer, phone_number VARCHAR(20), last_update TIMESTAMP);
